angular.module('viajeBusApp', ['ui.router','ui.bootstrap'])
    .service("UsuarioService", UsuarioService)
    .service("ViajeService", ViajeService)
    .controller('LoginController', LoginController)
    .controller('BuscarViajesController', BuscarViajesController)
    .config(routes)
