angular.module('viajeBusApp', ['ui.router','ui.bootstrap'])
    .service("UsuarioService", UsuarioService)
    .service("ViajeService", ViajeService)
    .service("BarraSuperiorService", BarraSuperiorService)
    .controller('LoginController', LoginController)
    .controller('RegisterController', RegisterController)
    .controller('BarraSuperiorController', BarraSuperiorController)
    .controller('BuscarViajesController', BuscarViajesController)
    .config(routes)
